package codegen_test

import (
	"context"
	"fmt"

	"go.yorun.ai/skel/api"
	"go.yorun.ai/skel/codegen"
)

func ExampleGeneratorFunc() {
	parsed, err := api.Parse(api.Input{SkelIn: "example.skel", Sources: map[string][]byte{
		"example.skel": []byte("domain demo\npub data User { name: string }\n"),
	}})
	if err != nil {
		panic(err)
	}
	input, err := codegen.Prepare(parsed.Domain, codegen.Selection{Surface: codegen.SurfacePublic})
	if err != nil {
		panic(err)
	}
	binding := codegen.GeneratorFunc(func(ctx context.Context, in codegen.Input) ([]codegen.File, error) {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		var source string
		for _, data := range in.Declarations().Data {
			source += "class " + data.Name + ":\n    pass\n"
		}
		return []codegen.File{{Path: "types.py", Content: source, CommentPrefix: "#"}}, nil
	})
	files, err := codegen.Generate(context.Background(), input, binding)
	if err != nil {
		panic(err)
	}
	fmt.Print(files[0].Content)
	// To publish: codegen.Run(ctx, input, binding, map[string]string{"": "./generated"}).
	// Output:
	// # Code generated by skelc. DO NOT EDIT.
	//
	// class User:
	//     pass
}
