package api_test

import (
	"encoding/json"
	"fmt"
	stdparser "go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"testing"

	skelapi "go.yorun.ai/skel/api"
	"go.yorun.ai/skel/internal/testutil"
	"go.yorun.ai/skel/schema"
	"golang.org/x/mod/modfile"
)

func TestGenerateGolang(t *testing.T) {
	skelDir := t.TempDir()
	goOut := filepath.Join(t.TempDir(), "generated")
	writeTestFile(t, filepath.Join(skelDir, "domain.skel"), "domain demo.user")
	writeTestFile(t, filepath.Join(goOut, "stale.go"), "// Code generated by skelc. DO NOT EDIT.\npackage generated\n")
	writeTestFile(t, filepath.Join(goOut, "custom.go"), "package generated\n")

	result, err := skelapi.CompileGolang(
		skelapi.Input{SkelIn: skelDir},
		skelapi.GolangOption{Out: goOut, CompilerVersion: "v1.2.3"},
	)
	if err != nil {
		t.Fatalf("generate Go: %v", err)
	}
	if len(result.Diagnostics) != 0 {
		t.Fatalf("unexpected diagnostics: %v", result.Diagnostics)
	}
	assertTestFileExists(t, filepath.Join(goOut, "doc.go"))
	assertTestFileExists(t, filepath.Join(goOut, "descriptor.go"))
	assertTestFileStartsWithGeneratedMarker(t, filepath.Join(goOut, "doc.go"))
	assertTestFileStartsWithGeneratedMarker(t, filepath.Join(goOut, "descriptor.go"))
	assertTestFileExists(t, filepath.Join(goOut, "custom.go"))
	if _, err := os.Stat(filepath.Join(goOut, "stale.go")); !os.IsNotExist(err) {
		t.Fatalf("stale generated file remains: %v", err)
	}
}

func TestCompileTargetsWithImportedDomainNamedTypeReferences(t *testing.T) {
	baseDir := t.TempDir()
	writeTestFile(t, filepath.Join(baseDir, "domain.skel"), "domain base")
	writeTestFile(t, filepath.Join(baseDir, "types.skel"), `
domain base

pub enum ItemType {
    STANDARD
}

pub data Item {
    type: ItemType
    types: list<ItemType>
    itemsByType: map<ItemType, Item>
}

pub config ItemConfig eternal {
    defaultType: ItemType
}

pub event ItemCreatedEvent {
    payload {
        item: Item
    }
}

pub actor BaseActor {
    via client {}
    auth {
        credential {
            subject: string
        }
        info {
            item: Item
        }
    }
}

pub resource ItemResource {
    check byItem {
        input {
            item: Item
        }
    }
    action read
}

api service BaseApiService { auth required
    for BaseActor

    method getItem {
        input {
            type: ItemType
        }
        output Item
    }
}

task SyncItemTask {
    trigger manually {
        input {
            item: Item
        }
    }
}
`)
	appDir := t.TempDir()
	writeTestFile(t, filepath.Join(appDir, "domain.skel"), "domain app")
	writeTestFile(t, filepath.Join(appDir, "types.skel"), `
domain app

import base

pub data AppItem {
    item: base.Item
    kind: base.ItemType
}
`)

	input := skelapi.Input{SkelIn: appDir, SkelImports: map[string]string{"base": baseDir}}
	tests := []struct {
		name     string
		file     string
		compile  func(out string) error
		expected []string
	}{
		{
			name: "Go",
			file: "data.go",
			compile: func(out string) error {
				_, err := skelapi.CompileGolang(input, skelapi.GolangOption{
					CompilerVersion: "v0.0.0-dev",
					Out:             out,
					Imports:         map[string]string{"base": "example.com/basepub"},
				})
				return err
			},
			expected: []string{"Item basepub.Item", "Kind basepub.ItemType"},
		},
		{
			name: "TypeScript",
			file: "data.ts",
			compile: func(out string) error {
				_, err := skelapi.CompileTypeScript(input, skelapi.TypeScriptOption{ApiOnly: true,
					Out:     out,
					Imports: map[string]string{"base": "@example/base"},
				})
				return err
			},
			expected: []string{"item: baseapi.Item;", "kind: baseapi.ItemType;"},
		},
		{
			name: "Skel",
			file: "types.skel",
			compile: func(out string) error {
				_, err := skelapi.CompileSkeleton(input, skelapi.SkeletonOption{
					Out:     out,
					PubOnly: true,
				})
				return err
			},
			expected: []string{"item: base.Item", "kind: base.ItemType"},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			// The Go generator derives the package name from the output
			// directory, so it must be a valid identifier.
			out := filepath.Join(t.TempDir(), "generated")
			if err := test.compile(out); err != nil {
				t.Fatalf("compile %s with imported named type references: %v", test.name, err)
			}
			content, err := os.ReadFile(filepath.Join(out, test.file))
			if err != nil {
				t.Fatalf("read generated %s: %v", test.file, err)
			}
			for _, fragment := range test.expected {
				if !strings.Contains(string(content), fragment) {
					t.Fatalf("generated %s missing %q:\n%s", test.file, fragment, content)
				}
			}
		})
	}
}

func TestCompileGolangAnalyzesTransitiveImportsButGeneratesOnlyTarget(t *testing.T) {
	baseDir := t.TempDir()
	writeTestFile(t, filepath.Join(baseDir, "domain.skel"), "domain base")
	writeTestFile(t, filepath.Join(baseDir, "types.skel"), `
domain base

pub enum UserStatus {
    ACTIVE
}
`)
	userDir := t.TempDir()
	writeTestFile(t, filepath.Join(userDir, "domain.skel"), "domain user")
	writeTestFile(t, filepath.Join(userDir, "types.skel"), `
domain user

import base

pub data User {
    status: base.UserStatus
}
`)
	appDir := t.TempDir()
	writeTestFile(t, filepath.Join(appDir, "domain.skel"), "domain app")
	writeTestFile(t, filepath.Join(appDir, "types.skel"), `
domain app

import user

data AppUser {
    user: user.User
}
`)

	goOut := filepath.Join(t.TempDir(), "generated")
	_, err := skelapi.CompileGolang(
		skelapi.Input{
			SkelIn: appDir,
			SkelImports: map[string]string{
				"base": baseDir,
				"user": userDir,
			},
		},
		skelapi.GolangOption{
			CompilerVersion: "v0.0.0-dev",
			Out:             goOut,
			Imports:         map[string]string{"user": "example.com/userpub"},
		},
	)
	if err != nil {
		t.Fatalf("compile Go with transitive imports: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(goOut, "data.go"))
	if err != nil {
		t.Fatalf("read generated target data: %v", err)
	}
	generated := string(content)
	if !strings.Contains(generated, "type AppUser struct") {
		t.Fatalf("target data was not generated:\n%s", generated)
	}
	if strings.Contains(generated, "type User struct") || strings.Contains(generated, "type UserStatus ") {
		t.Fatalf("dependency declarations were generated into target output:\n%s", generated)
	}
}

func TestGenerateTargetsShareParsedDomain(t *testing.T) {
	skelDir := t.TempDir()
	writeTestFile(t, filepath.Join(skelDir, "domain.skel"), "domain demo.user")

	parsed, err := skelapi.Parse(skelapi.Input{SkelIn: skelDir})
	if err != nil {
		t.Fatalf("parse Skel: %v", err)
	}
	goOut := filepath.Join(t.TempDir(), "golang")
	if err := skelapi.GenerateGolang(parsed.Domain, skelapi.GolangOption{CompilerVersion: "v0.0.0-dev", Out: goOut}); err != nil {
		t.Fatalf("generate Go: %v", err)
	}
	tsOut := filepath.Join(t.TempDir(), "typescript")
	if err := skelapi.GenerateTypeScript(parsed.Domain, skelapi.TypeScriptOption{ApiOnly: true, Out: tsOut}); err != nil {
		t.Fatalf("generate TypeScript: %v", err)
	}
	assertTestFileExists(t, filepath.Join(goOut, "descriptor.go"))
	assertTestFileExists(t, filepath.Join(tsOut, "index.ts"))
	assertTestFileStartsWithGeneratedMarker(t, filepath.Join(tsOut, "index.ts"))
}

func TestGenerateTypeScript(t *testing.T) {
	skelDir := t.TempDir()
	tsOut := filepath.Join(t.TempDir(), "generated")
	writeTestFile(t, filepath.Join(skelDir, "domain.skel"), "domain demo.user")

	_, err := skelapi.CompileTypeScript(
		skelapi.Input{SkelIn: skelDir},
		skelapi.TypeScriptOption{ApiOnly: true, Out: tsOut},
	)
	if err != nil {
		t.Fatalf("generate TypeScript: %v", err)
	}
	assertTestFileExists(t, filepath.Join(tsOut, "index.ts"))
}

func TestGenerateSkeleton(t *testing.T) {
	skelDir := t.TempDir()
	skelOut := filepath.Join(t.TempDir(), "generated")
	writeTestFile(t, filepath.Join(skelDir, "domain.skel"), "domain demo.user")

	_, err := skelapi.CompileSkeleton(
		skelapi.Input{SkelIn: skelDir},
		skelapi.SkeletonOption{Out: skelOut, PubOnly: true},
	)
	if err != nil {
		t.Fatalf("generate Skel: %v", err)
	}
	assertTestFileExists(t, filepath.Join(skelOut, "domain.skel"))
	assertTestFileStartsWithGeneratedMarker(t, filepath.Join(skelOut, "domain.skel"))
	if _, err := skelapi.Parse(skelapi.Input{SkelIn: skelOut}); err != nil {
		t.Fatalf("parse generated Skel with ownership marker: %v", err)
	}
}

func TestGenerateGolangReturnsErrorBeforeCleaningOutput(t *testing.T) {
	skelDir := t.TempDir()
	goOut := filepath.Join(t.TempDir(), "generated")
	writeTestFile(t, filepath.Join(skelDir, "invalid.skel"), "data User { id: string }")
	oldFile := filepath.Join(goOut, "old.go")
	writeTestFile(t, oldFile, "old")

	_, err := skelapi.CompileGolang(
		skelapi.Input{SkelIn: skelDir},
		skelapi.GolangOption{CompilerVersion: "v0.0.0-dev", Out: goOut},
	)
	if err == nil {
		t.Fatal("expected generation error")
	}
	assertTestFileExists(t, oldFile)
}

func TestGeneratorsReturnErrorsForMalformedProgrammaticSchemas(t *testing.T) {
	domain := schema.NewDomainFromSpec(schema.DomainSpec{
		Name: "demo.invalid",
		Data: []*schema.Data{{
			Name: "Broken",
			Pub:  true,
			Members: []*schema.DataMember{{
				Name: "value",
				Type: &schema.Type{Kind: schema.TypeKind(999)},
			}},
		}},
	})
	tests := []struct {
		name     string
		generate func() error
	}{
		{
			name: "Go",
			generate: func() error {
				return skelapi.GenerateGolang(domain, skelapi.GolangOption{CompilerVersion: "v0.0.0-dev", Out: filepath.Join(t.TempDir(), "generated")})
			},
		},
		{
			name: "TypeScript",
			generate: func() error {
				return skelapi.GenerateTypeScript(domain, skelapi.TypeScriptOption{ApiOnly: true, Out: t.TempDir()})
			},
		},
		{
			name: "Skel",
			generate: func() error {
				return skelapi.GenerateSkeleton(domain, skelapi.SkeletonOption{Out: t.TempDir(), PubOnly: true})
			},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			err := test.generate()
			if err == nil || !strings.Contains(err.Error(), "unsupported type kind 999") {
				t.Fatalf("expected malformed schema error, got %v", err)
			}
		})
	}
}

func TestGeneratorsReturnErrorsForMalformedNestedSchemas(t *testing.T) {
	domains := []struct {
		name     string
		domain   *schema.Domain
		expected string
	}{
		{
			name: "incomplete actor auth",
			domain: schema.NewDomainFromSpec(schema.DomainSpec{
				Name: "demo.invalid", Actors: []*schema.Actor{{Name: "Client", Auth: new(schema.ActorAuth{})}},
			}),
			expected: "incomplete auth support",
		},
		{
			name: "nil import",
			domain: schema.NewDomainFromSpec(schema.DomainSpec{
				Name: "demo.invalid", Imports: []*schema.Import{nil},
			}),
			expected: "nil import",
		},
	}
	for _, malformed := range domains {
		t.Run(malformed.name, func(t *testing.T) {
			generators := []struct {
				name     string
				generate func() error
			}{
				{name: "Go", generate: func() error {
					return skelapi.GenerateGolang(malformed.domain, skelapi.GolangOption{CompilerVersion: "v0.0.0-dev", Out: filepath.Join(t.TempDir(), "generated")})
				}},
				{name: "TypeScript", generate: func() error {
					return skelapi.GenerateTypeScript(malformed.domain, skelapi.TypeScriptOption{ApiOnly: true, Out: t.TempDir()})
				}},
				{name: "Skel", generate: func() error {
					return skelapi.GenerateSkeleton(malformed.domain, skelapi.SkeletonOption{Out: t.TempDir(), PubOnly: true})
				}},
			}
			for _, generator := range generators {
				t.Run(generator.name, func(t *testing.T) {
					err := generator.generate()
					if err == nil || !strings.Contains(err.Error(), malformed.expected) {
						t.Fatalf("expected error containing %q, got %v", malformed.expected, err)
					}
				})
			}
		})
	}
}

func TestGeneratorsRejectNilTypeParameter(t *testing.T) {
	domain := schema.NewDomainFromSpec(schema.DomainSpec{Name: "demo.invalid", Data: []*schema.Data{{Name: "Box", SkelName: "demo.invalid.Box", Kind: schema.DataKindData, Pub: true, TypeParameters: []*schema.TypeParameter{nil}}}})
	for _, target := range []string{"Go", "TypeScript", "Skel"} {
		t.Run(target, func(t *testing.T) {
			out := filepath.Join(t.TempDir(), "generated")
			if err := os.Mkdir(out, 0o755); err != nil {
				t.Fatal(err)
			}
			var err error
			switch target {
			case "Go":
				err = skelapi.GenerateGolang(domain, skelapi.GolangOption{CompilerVersion: "v0.0.0-dev", Out: out})
			case "TypeScript":
				err = skelapi.GenerateTypeScript(domain, skelapi.TypeScriptOption{ApiOnly: true, Out: out})
			case "Skel":
				err = skelapi.GenerateSkeleton(domain, skelapi.SkeletonOption{PubOnly: true, Out: out})
			}
			if err == nil || !strings.Contains(err.Error(), "nil type parameter") {
				t.Fatalf("expected invalid schema error, got %v", err)
			}
			entries, err := os.ReadDir(out)
			if err != nil || len(entries) != 0 {
				t.Fatalf("invalid schema wrote output: %v, %v", entries, err)
			}
		})
	}
}

// b's public contract needs c for parsing, even when a uses only b.Token or its actor.
func TestCompileModulesSeparateResolutionMappingsFromDependencies(t *testing.T) {
	for _, tc := range []struct {
		name, source               string
		full, public, regular, api []string
	}{
		{"external actor", "pub data Payload { id: uuid }\nweb GatewayWeb { auth required  for b.AgentActor }", nil, nil, nil, nil},
		{"unused transitive contract", "pub data Payload { token: b.Token }", []string{"b"}, []string{"b"}, nil, []string{"b"}},
		{"split output boundaries", "pub data Payload { access: c.Access }\ndata PrivatePayload { token: b.Token }", []string{"b", "c"}, []string{"c"}, []string{"b"}, []string{"c"}},
		{"generic arguments", "pub data Payload { values: map<string, b.Box<c.Access>> }", []string{"b", "c"}, []string{"b", "c"}, nil, []string{"b", "c"}},
		{"public service implementation", "pub service ExampleService { method get { output b.Token } }", []string{"b"}, []string{"b"}, []string{"b"}, nil},
		{"actor and resource helpers", `pub actor LocalActor {
    via client {}
    auth { credential { token: string } info { access: c.Access } }
}
pub resource LocalResource {
    check byToken { input { token: b.Token } }
    action read
}
api service ExampleApiService { auth required  for LocalActor via client method ping {} }`, []string{"b", "c"}, []string{"b", "c"}, nil, nil},
		{"config event and task", `pub config ExampleConfig eternal { token: b.Token }
pub event ExampleEvent { payload { access: c.Access } }
task ExampleTask { trigger manually { input { token: b.Token } } }`, []string{"b", "c"}, []string{"b", "c"}, []string{"b", "c"}, nil},
	} {
		t.Run(tc.name, func(t *testing.T) {
			root := t.TempDir()
			a, b, c := filepath.Join(root, "a.skel"), filepath.Join(root, "b.skel"), filepath.Join(root, "c.skel")
			imports := "import b\n"
			if strings.Contains(tc.source, "c.") {
				imports += "import c\n"
			}
			writeTestFile(t, a, "domain a\n"+imports+tc.source+"\n")
			writeTestFile(t, b, "domain b\nimport c\npub data Token { id: uuid access: c.Access }\npub data Box<TItem> { items: list<TItem> }\npub actor AgentActor { via client {} }\npub service AccessService { method get { output c.Access } }\n")
			writeTestFile(t, c, "domain c\npub data Access { id: uuid }\n")
			input := skelapi.Input{SkelIn: a, SkelImports: map[string]string{"b": b, "c": c}}
			mappings := map[string]string{"b": "example.com/bpub@v1.2.3", "c": "example.com/cpub@v1.3.0", "unused": "example.com/unused@v1.4.0"}
			dependencyOutputs := map[bool]map[string]string{}
			for _, api := range []bool{false, true} {
				dependencyOutputs[api] = map[string]string{}
				for name, entry := range map[string]string{"b": b, "c": c} {
					out := filepath.Join(root, map[bool]string{false: "pubdeps", true: "apideps"}[api], name)
					dependencyImports := map[string]string{}
					if name == "b" {
						dependencyImports["c"] = c
					}
					if _, err := skelapi.CompileGolang(skelapi.Input{SkelIn: entry, SkelImports: dependencyImports}, skelapi.GolangOption{
						CompilerVersion: "v0.0.0-dev", PubOnly: !api, ApiOnly: api, AsModule: true, Module: "example.com/" + name + "pub", Out: out, Imports: mappings,
					}); err != nil {
						t.Fatal(err)
					}
					dependencyOutputs[api][name] = out
				}
			}
			for _, mode := range []string{"full", "pub", "api", "split"} {
				t.Run(mode, func(t *testing.T) {
					out := filepath.Join(root, mode)
					opts := skelapi.GolangOption{CompilerVersion: "v0.0.0-dev", AsModule: true, Module: "example.com/a", Out: out, Imports: mappings}
					want := tc.full
					switch mode {
					case "pub":
						opts.PubOnly = true
						want = tc.public
					case "api":
						opts.ApiOnly = true
						want = tc.api
					case "split":
						opts.PubOut = out + "pub"
						opts.PubModule = "example.com/apub"
						want = tc.regular
					}
					if _, err := skelapi.CompileGolang(input, opts); err != nil {
						t.Fatal(err)
					}
					assertGeneratedDomainRequires(t, out, want)
					if mode == "split" {
						assertGeneratedDomainRequires(t, opts.PubOut, tc.public)
						content, err := os.ReadFile(filepath.Join(out, "go.mod"))
						if err != nil {
							t.Fatal(err)
						}
						if !strings.Contains(string(content), "example.com/apub ") {
							t.Fatal("split output lost its own public-module dependency")
						}
					}
					t.Run("compile", func(t *testing.T) {
						testutil.RequireToolchain(t)
						// Use generated local dependencies; go.work must not hide a
						// missing requirement in any generated module.
						for name, dir := range dependencyOutputs[mode == "api"] {
							testutil.Go(t, out, "mod", "edit", "-replace=example.com/"+name+"pub="+dir)
						}
						if mode == "split" {
							testutil.Go(t, out, "mod", "edit", "-replace=example.com/apub="+opts.PubOut)
						}
						testutil.UseLocalSkel(t, out)
						testutil.Go(t, out, "mod", "tidy")
						files, err := filepath.Glob(filepath.Join(out, "*.go"))
						if err != nil {
							t.Fatal(err)
						}
						if len(files) > 0 {
							testutil.Go(t, out, "test", "./...")
						}
					})
				})
			}
			tsOut := filepath.Join(root, "ts")
			if _, err := skelapi.CompileTypeScript(input, skelapi.TypeScriptOption{ApiOnly: true, AsModule: true, Module: "@example/a", Out: tsOut, Imports: map[string]string{"b": "@example/b@1.2.3", "c": "@example/c@1.3.0", "unused": "@example/unused@1.4.0"}}); err != nil {
				t.Fatal(err)
			}
			manifest, err := os.ReadFile(filepath.Join(tsOut, "package.json"))
			if err != nil {
				t.Fatal(err)
			}
			for _, name := range []string{"b", "c", "unused"} {
				want := false
				for _, dep := range tc.api {
					want = want || dep == name
				}
				if strings.Contains(string(manifest), `"@example/`+name+`"`) != want {
					t.Fatalf("wrong TypeScript dependency %s: %s", name, manifest)
				}
			}
			if mappings["unused"] != "example.com/unused@v1.4.0" || len(mappings) != 3 {
				t.Fatal("generation mutated caller's import mappings")
			}
		})
	}
}

func assertGeneratedDomainRequires(t *testing.T, out string, want []string) {
	t.Helper()
	content, err := os.ReadFile(filepath.Join(out, "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	file, err := modfile.Parse("go.mod", content, nil)
	if err != nil {
		t.Fatal(err)
	}
	requires := map[string]string{}
	for _, require := range file.Require {
		requires[require.Mod.Path] = require.Mod.Version
	}
	// Cross-check schema-based dependencies against independently parsed output.
	paths := map[string]bool{}
	files, err := filepath.Glob(filepath.Join(out, "*.go"))
	if err != nil {
		t.Fatal(err)
	}
	for _, path := range files {
		parsed, err := stdparser.ParseFile(token.NewFileSet(), path, nil, stdparser.ImportsOnly)
		if err != nil {
			t.Fatal(err)
		}
		for _, spec := range parsed.Imports {
			path, err := strconv.Unquote(spec.Path.Value)
			if err != nil {
				t.Fatal(err)
			}
			paths[path] = true
		}
	}
	for _, path := range []string{"example.com/bpub", "example.com/cpub", "example.com/unused"} {
		if paths[path] != (requires[path] != "") {
			t.Fatalf("dependency %s disagrees with generated imports: %s", path, content)
		}
	}
	for name, version := range map[string]string{"b": "v1.2.3", "c": "v1.3.0", "unused": "v1.4.0"} {
		used := false
		for _, dep := range want {
			used = used || dep == name
		}
		got := requires["example.com/"+name+"pub"]
		if name == "unused" {
			got = requires["example.com/unused"]
		}
		if used && got != version || !used && got != "" {
			t.Fatalf("dependency %s = %q, used=%v: %s", name, got, used, content)
		}
	}
}

func TestCompileGolangIncludesUsedPrefixDerivedDependencies(t *testing.T) {
	for _, api := range []bool{false, true} {
		t.Run(map[bool]string{false: "backend", true: "api"}[api], func(t *testing.T) {
			root := t.TempDir()
			a, b := filepath.Join(root, "a.skel"), filepath.Join(root, "b.skel")
			writeTestFile(t, a, "domain a\nimport b\npub data Payload { token: b.Token }\n")
			writeTestFile(t, b, "domain b\npub data Token { id: string }\n")
			out := filepath.Join(root, "out")
			if _, err := skelapi.CompileGolang(skelapi.Input{SkelIn: a, SkelImports: map[string]string{"b": b}}, skelapi.GolangOption{CompilerVersion: "v0.0.0-dev", ApiOnly: api, AsModule: true, ModulePrefix: "example.com/gen", Out: out}); err != nil {
				t.Fatal(err)
			}
			content, err := os.ReadFile(filepath.Join(out, "go.mod"))
			if err != nil {
				t.Fatal(err)
			}
			suffix := map[bool]string{false: "pub", true: "api"}[api]
			if !strings.Contains(string(content), "example.com/gen/b"+suffix+" v0.0.0-00010101000000-000000000000") {
				t.Fatalf("missing inferred dependency: %s", content)
			}
		})
	}
}

func TestCompileGolangDependencyConflictCompatibility(t *testing.T) {
	for _, api := range []bool{false, true} {
		for _, used := range []int{0, 1, 2} {
			t.Run(fmt.Sprintf("api=%v/used=%d", api, used), func(t *testing.T) {
				root := t.TempDir()
				a := filepath.Join(root, "a.skel")
				first, second := filepath.Join(root, "first.skel"), filepath.Join(root, "second.skel")
				writeTestFile(t, first, "domain first\npub data Value { id: string }\n")
				writeTestFile(t, second, "domain second\npub data Value { id: string }\n")
				source := "domain a\nimport first\nimport second\npub data Payload { id: string\n"
				if used > 0 {
					source += "first: first.Value\n"
				}
				if used > 1 {
					source += "second: second.Value\n"
				}
				writeTestFile(t, a, source+"}\n")
				out := filepath.Join(root, "out")
				sentinel := filepath.Join(out, "sentinel.go")
				original := "// Code generated by skelc. DO NOT EDIT.\npackage sentinel\n"
				writeTestFile(t, sentinel, original)
				_, err := skelapi.CompileGolang(skelapi.Input{SkelIn: a, SkelImports: map[string]string{"first": first, "second": second}}, skelapi.GolangOption{
					CompilerVersion: "v0.0.0-dev", ApiOnly: api, AsModule: true, Module: "example.com/a", Out: out,
					Imports: map[string]string{"first": "example.com/shared@v1.0.0", "second": "example.com/shared@v1.1.0"},
				})
				if !api || used == 2 {
					if err == nil || !strings.Contains(err.Error(), "conflicting") {
						t.Fatalf("expected dependency conflict, got %v", err)
					}
					got, readErr := os.ReadFile(sentinel)
					if readErr != nil || string(got) != original {
						t.Fatalf("conflict changed existing output: %s, %v", got, readErr)
					}
					return
				}
				if err != nil {
					t.Fatal(err)
				}
				content, err := os.ReadFile(filepath.Join(out, "go.mod"))
				if err != nil {
					t.Fatal(err)
				}
				if strings.Contains(string(content), "example.com/shared v1.0.0") != (used == 1) || strings.Contains(string(content), "v1.1.0") {
					t.Fatalf("unused mapping affected API dependencies: %s", content)
				}
			})
		}
	}
}

func TestPublicOptionsRejectEmptyImportMappings(t *testing.T) {
	if _, err := skelapi.Parse(skelapi.Input{SkelIn: "input.skel", SkelImports: map[string]string{"demo.user": ""}}); err == nil {
		t.Fatal("expected empty Skel import path error")
	}
	domain := schema.NewDomainFromSpec(schema.DomainSpec{Name: "demo.test"})
	if err := skelapi.GenerateGolang(domain, skelapi.GolangOption{
		CompilerVersion: "v0.0.0-dev",
		Out:             filepath.Join(t.TempDir(), "golang"), Imports: map[string]string{"demo.user": ""},
	}); err == nil {
		t.Fatal("expected empty Go import path error")
	}
	if err := skelapi.GenerateTypeScript(domain, skelapi.TypeScriptOption{ApiOnly: true,
		Out: filepath.Join(t.TempDir(), "typescript"), Imports: map[string]string{"demo.user": ""},
	}); err == nil {
		t.Fatal("expected empty TypeScript import path error")
	}
}

func TestCompileNormalizesGenerationOptionsBeforeReadingInput(t *testing.T) {
	missingInput := skelapi.Input{SkelIn: filepath.Join(t.TempDir(), "missing")}
	tests := []struct {
		name     string
		compile  func() error
		expected string
	}{
		{
			name: "Go",
			compile: func() error {
				_, err := skelapi.CompileGolang(missingInput, skelapi.GolangOption{CompilerVersion: "v0.0.0-dev"})
				return err
			},
			expected: "Go output is required",
		},
		{
			name: "TypeScript",
			compile: func() error {
				_, err := skelapi.CompileTypeScript(missingInput, skelapi.TypeScriptOption{ApiOnly: true})
				return err
			},
			expected: "TypeScript output is required",
		},
		{
			name: "Skel",
			compile: func() error {
				_, err := skelapi.CompileSkeleton(missingInput, skelapi.SkeletonOption{})
				return err
			},
			expected: "Skel output is required",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if err := test.compile(); err == nil || !strings.Contains(err.Error(), test.expected) {
				t.Fatalf("expected %q before input loading, got %v", test.expected, err)
			}
		})
	}
}

func TestGeneratorsReturnErrorsForMissingExternalImportMappings(t *testing.T) {
	userDir := t.TempDir()
	writeTestFile(t, filepath.Join(userDir, "domain.skel"), "domain demo.user")
	writeTestFile(t, filepath.Join(userDir, "user.skel"), "domain demo.user\npub data User { id: string }")
	orderDir := t.TempDir()
	writeTestFile(t, filepath.Join(orderDir, "domain.skel"), "domain demo.order")
	writeTestFile(t, filepath.Join(orderDir, "order.skel"), "domain demo.order\nimport demo.user as user\npub data Order { user: user.User }")

	parsed, err := skelapi.Parse(skelapi.Input{
		SkelIn:      orderDir,
		SkelImports: map[string]string{"demo.user": userDir},
	})
	if err != nil {
		t.Fatalf("parse imported domain: %v", err)
	}

	goErr := skelapi.GenerateGolang(parsed.Domain, skelapi.GolangOption{CompilerVersion: "v0.0.0-dev", Out: filepath.Join(t.TempDir(), "golang")})
	if goErr == nil || !strings.Contains(goErr.Error(), "missing Go import for domain demo.user") {
		t.Fatalf("expected missing Go import error, got %v", goErr)
	}
	tsErr := skelapi.GenerateTypeScript(parsed.Domain, skelapi.TypeScriptOption{ApiOnly: true, Out: filepath.Join(t.TempDir(), "typescript")})
	if tsErr == nil || !strings.Contains(tsErr.Error(), "missing TypeScript import for domain demo.user") {
		t.Fatalf("expected missing TypeScript import error, got %v", tsErr)
	}
}

func TestBackendGenerationRejectsInvalidCompilerVersionBeforeWriting(t *testing.T) {
	for _, version := range []string{"", "  ", "invalid", "0.19.2", "v01.19.2", "v0.19", "v0.14.0", "v0.17.0", "v0.17.1-rc.1"} {
		t.Run(version, func(t *testing.T) {
			root := t.TempDir()
			source := filepath.Join(root, "input.skel")
			if err := os.WriteFile(source, []byte("domain demo.example\npub data Value { name: string }\n"), 0600); err != nil {
				t.Fatal(err)
			}
			out := filepath.Join(root, "generated")
			if err := os.Mkdir(out, 0700); err != nil {
				t.Fatal(err)
			}
			sentinel := filepath.Join(out, "data.go")
			original := "// Code generated by skelc. DO NOT EDIT.\npackage original\n"
			if err := os.WriteFile(sentinel, []byte(original), 0600); err != nil {
				t.Fatal(err)
			}
			input := skelapi.Input{SkelIn: source}
			option := skelapi.GolangOption{Out: out, CompilerVersion: version}
			if _, err := skelapi.CompileGolang(input, option); err == nil {
				t.Fatal("accepted invalid compiler version")
			}
			domain, err := skelapi.Parse(input)
			if err != nil {
				t.Fatal(err)
			}
			if err := skelapi.GenerateGolang(domain.Domain, option); err == nil {
				t.Fatal("GenerateGolang accepted invalid compiler version")
			}
			data, err := os.ReadFile(sentinel)
			if err != nil || string(data) != original {
				t.Fatalf("output changed: %s, %v", data, err)
			}
		})
	}
}

func TestImportValidationOrderIsDeterministic(t *testing.T) {
	domain := schema.NewDomainFromSpec(schema.DomainSpec{Name: "demo.test"})
	imports := map[string]string{"z": "example.com/z@", "a": "example.com/a@"}
	out := filepath.Join(t.TempDir(), "generated")
	for range 30 {
		goErr := skelapi.GenerateGolang(domain, skelapi.GolangOption{Out: out, CompilerVersion: "v0.0.0-dev", Imports: imports})
		tsErr := skelapi.GenerateTypeScript(domain, skelapi.TypeScriptOption{Out: out, ApiOnly: true, Imports: imports})
		for _, err := range []error{goErr, tsErr} {
			if err == nil || !strings.Contains(err.Error(), "example.com/a@") {
				t.Fatalf("unstable first error: %v", err)
			}
		}
	}
}

func TestApiPruneQueryAndGeneration(t *testing.T) {
	root := t.TempDir()
	entry, foreign, unused, deep := filepath.Join(root, "entry.skel"), filepath.Join(root, "foreign.skel"), filepath.Join(root, "unused.skel"), filepath.Join(root, "deep.skel")
	writeTestFile(t, deep, "domain deep\npub data Detail { text: string }\n")
	writeTestFile(t, foreign, `domain foreign
import deep
pub data Box<TItem> { value: TItem }
pub data Money { amount: int detail: deep.Detail }
pub enum Currency { USD EUR }
`)
	writeTestFile(t, unused, "domain unused\npub data Secret { value: string }\n")
	writeTestFile(t, entry, `domain shop.order
import foreign as f
import unused
actor UserActor { via client {} }
actor AdminActor { via client {} }
actor IdleActor { via client {} }
pub data Unused { secret: unused.Secret }
pub enum UnusedEnum { ONE TWO }
data Node { next: Peer? value: f.Money currency: f.Currency }
data Peer { next: Node? values: map<string,list<f.Money?>> }
pub data Extra { value: string }
api service UserApiService {
 for UserActor via client
 auth anonymous
 method read { output f.Box<list<Node>> }
}
api service AdminApiService {
 for AdminActor via client
 auth anonymous
 method read { output Unused }
}
`)
	input := skelapi.Input{SkelIn: entry, SkelImports: map[string]string{"foreign": foreign, "unused": unused, "deep": deep}}
	actor := []string{"shop.order.UserActor"}
	selection := skelapi.ApiFilter{Prune: true, Actors: actor}
	result, err := skelapi.QueryApiDependencies(input, selection)
	if err != nil {
		t.Fatal(err)
	}
	want := &skelapi.ApiDependencyReport{Domain: "shop.order", Services: []string{"shop.order.UserApiService"}, Data: []string{"shop.order.Node", "shop.order.Peer"}, Enums: []string{}, Dependencies: []skelapi.ApiTypeDependency{{Domain: "foreign", Name: "Box", Kind: "data"}, {Domain: "foreign", Name: "Currency", Kind: "enum"}, {Domain: "foreign", Name: "Money", Kind: "data"}}}
	if !reflect.DeepEqual(result.Report, want) {
		t.Fatalf("report=%+v, want %+v", result.Report, want)
	}
	// Foreign members belong to a separate query; aliases never appear in reports.
	next, err := skelapi.QueryApiDependencies(skelapi.Input{SkelIn: foreign, SkelImports: map[string]string{"deep": deep}}, skelapi.ApiFilter{Prune: true, Types: []string{"foreign.Money"}})
	if err != nil || len(next.Report.Dependencies) != 1 || next.Report.Dependencies[0].Domain != "deep" {
		t.Fatalf("foreign closure: %+v, %v", next, err)
	}
	union := skelapi.ApiFilter{Prune: true, Actors: actor, Types: []string{"shop.order.Extra", "shop.order.UnusedEnum", "shop.order.Extra"}}
	combined, err := skelapi.QueryApiDependencies(input, union)
	if err != nil || len(combined.Report.Data) != 3 || len(combined.Report.Enums) != 1 {
		t.Fatalf("union: %+v, %v", combined, err)
	}
	empty, err := skelapi.QueryApiDependencies(input, skelapi.ApiFilter{Prune: true, Actors: []string{"shop.order.IdleActor"}})
	if err != nil {
		t.Fatal(err)
	}
	encoded, _ := json.Marshal(empty.Report)
	if strings.Contains(string(encoded), "null") || len(empty.Report.Data) != 0 {
		t.Fatalf("empty selection: %s", encoded)
	}
	// Root order and repeated roots must not affect either the report or output.
	ordered := skelapi.ApiFilter{Prune: true, Actors: []string{"shop.order.UserActor", "shop.order.AdminActor"}, Types: []string{"shop.order.Extra", "shop.order.UnusedEnum"}}
	reordered := skelapi.ApiFilter{Prune: true, Actors: []string{"shop.order.AdminActor", "shop.order.UserActor", "shop.order.AdminActor"}, Types: []string{"shop.order.UnusedEnum", "shop.order.Extra", "shop.order.UnusedEnum"}}
	first, err := skelapi.QueryApiDependencies(input, ordered)
	if err != nil {
		t.Fatal(err)
	}
	second, err := skelapi.QueryApiDependencies(input, reordered)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(first.Report, second.Report) {
		t.Fatalf("root order changed dependency report: %+v vs %+v", first.Report, second.Report)
	}
	for _, target := range []string{"go", "go-module", "ts", "ts-module"} {
		t.Run(target, func(t *testing.T) {
			out := filepath.Join(t.TempDir(), "api")
			generate := func(filter skelapi.ApiFilter) error {
				if strings.HasPrefix(target, "go") {
					_, err := skelapi.CompileGolang(input, skelapi.GolangOption{ApiOnly: true, ApiFilter: filter, Out: out, AsModule: target == "go-module", Module: moduleForTarget(target, "example.com/orderapi"), Imports: map[string]string{"foreign": "example.com/foreignapi", "unused": "example.com/unusedapi"}})
					return err
				}
				_, err := skelapi.CompileTypeScript(input, skelapi.TypeScriptOption{ApiOnly: true, ApiFilter: filter, Out: out, AsModule: target == "ts-module", Module: moduleForTarget(target, "@demo/orderapi"), Imports: map[string]string{"foreign": "@demo/foreignapi", "unused": "@demo/unusedapi"}})
				return err
			}
			read := func() string {
				var contents []string
				err := filepath.WalkDir(out, func(path string, d os.DirEntry, err error) error {
					if err != nil {
						return err
					}
					if !d.IsDir() {
						data, e := os.ReadFile(path)
						if e != nil {
							return e
						}
						contents = append(contents, string(data))
					}
					return nil
				})
				if err != nil {
					t.Fatal(err)
				}
				return strings.Join(contents, "\n")
			}
			if err := generate(skelapi.ApiFilter{Actors: actor}); err != nil {
				t.Fatal(err)
			}
			if !strings.Contains(read(), "Unused") {
				t.Fatal("default public types were pruned")
			}
			if err := generate(selection); err != nil {
				t.Fatal(err)
			}
			text := read()
			for _, name := range []string{"Unused", "UnusedEnum", "AdminApiService", "unusedapi", "Extra"} {
				if strings.Contains(text, name) {
					t.Fatalf("retained %s", name)
				}
			}
			if !strings.Contains(text, "Node") || !strings.Contains(text, "UserApiService") {
				t.Fatal("missing selected declarations")
			}
			if err := generate(skelapi.ApiFilter{Prune: true, Types: []string{"shop.order.Extra"}}); err != nil {
				t.Fatal(err)
			}
			text = read()
			if !strings.Contains(text, "Extra") || strings.Contains(text, "UserApiService") || strings.Contains(text, "Node") || strings.Contains(text, "foreignapi") {
				t.Fatal("types-only output retained unrelated declarations or dependencies")
			}
			if err := generate(skelapi.ApiFilter{Prune: true, Types: []string{"shop.order.Missing"}}); err == nil {
				t.Fatal("unknown type accepted")
			}
			if read() != text {
				t.Fatal("invalid selection changed existing output")
			}
			if err := generate(ordered); err != nil {
				t.Fatal(err)
			}
			before := apiOutputSnapshot(t, out)
			if err := generate(reordered); err != nil {
				t.Fatal(err)
			}
			if after := apiOutputSnapshot(t, out); !reflect.DeepEqual(before, after) {
				t.Fatal("root order changed generated file paths or contents")
			}

			// Enum-only output must remove previous services, data and package dependencies.
			if err := generate(skelapi.ApiFilter{Prune: true, Types: []string{"shop.order.UnusedEnum"}}); err != nil {
				t.Fatal(err)
			}
			text = read()
			if !strings.Contains(text, "UnusedEnum") {
				t.Fatal("enum-only output omitted the selected enum")
			}
			for _, stale := range []string{"UserApiService", "AdminApiService", "Node", "Peer", "Extra", "foreignapi", "unusedapi"} {
				if strings.Contains(text, stale) {
					t.Fatalf("enum-only output retained %s", stale)
				}
			}

			// Export a populated view before selecting an actor with no services.
			if err := generate(ordered); err != nil {
				t.Fatal(err)
			}
			writeTestFile(t, filepath.Join(out, "user-note.txt"), "keep handwritten file")
			idle := skelapi.ApiFilter{Prune: true, Actors: []string{"shop.order.IdleActor"}}
			if err := generate(idle); err != nil {
				t.Fatal(err)
			}
			cleared := apiOutputSnapshot(t, out)
			if cleared["user-note.txt"] != "keep handwritten file" {
				t.Fatal("empty selection removed user content")
			}
			delete(cleared, "user-note.txt")
			// Equality with a fresh empty export detects stale files, barrel entries,
			// Go requirements and package.json dependencies without fixing a file layout.
			out = filepath.Join(t.TempDir(), "api")
			if err := generate(idle); err != nil {
				t.Fatal(err)
			}
			if fresh := apiOutputSnapshot(t, out); !reflect.DeepEqual(cleared, fresh) {
				t.Fatalf("empty selection retained stale output: cleared=%v fresh=%v", cleared, fresh)
			}

		})
	}
}

func moduleForTarget(target, module string) string {
	if strings.HasSuffix(target, "-module") {
		return module
	}
	return ""
}
